### ISSUE TITLE
Add Kubernetes Monitoring Template

### ISSUE THREAD

**Issue by russorat** [influxdata/community-templates#20]
Is your template request related to a problem? Please describe.
I would like to monitor my Kubernetes cluster.

Describe the solution you'd like
a set of configs, dashboards, and checks for monitoring kubernetes cluster

Additional context
None

**Comment by alsargent** [comment]
@russorat @samhld  For the sake of launch planning and messaging, do we have an ETA of when this will be published and publicly available?
