### ISSUE TITLE
Update CSGO Template with new Telegraf plugin

### ISSUE THREAD

**Issue by sjwang90** [influxdata/community-templates#242]
New plugin in Telegraf 1.18: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/csgo

See if the template can seamlessly use the Telegraf CS:GO plugin? 

@xe-nvdk

**Comment by xe-nvdk** [comment]
Nope. Is different. The template get data for the player on the CSGO official servers and the plugin is to get stats for a own hosted server.

**Comment by sjwang90** [comment]
Oh okay i'll close this then.
