### ISSUE TITLE
Influxdb2 Cardinality Now  wrong readme

### ISSUE THREAD

**Issue by Ob1A** [influxdata/community-templates#245]
**Template**: Provide the template name here
influxdb2_cardinality_now
**Describe the problem**
readme.md correspond to InfluxDB 2 Operational Monitoring

**Comment by Anaisdg** [comment]
@Ob1A I'm sorry can you explain the issue with some more detail please? The readme for the influxdb 2 operational monitoring template repo contains a section for the cardinality now template as well as the influxdb operational monitoring template as they are very similar. 

https://github.com/influxdata/community-templates/tree/master/influxdb2_operational_monitoring#cardinality-now

**Comment by Ob1A** [comment]
In the readme, link to influxdb2_cardinality_now.yml was broken.
(I agree that my explaination was a bit fuzzy)

It has been fixed since then :  https://github.com/influxdata/community-templates/commit/558d8fc2992a7a098eff1e4519f6ea5495be8de5#diff-7465142b095490926d4e3b106641958943373ac642040c0030f996c767b9b307
