### ISSUE TITLE
Add Kafka monitoring template

### ISSUE THREAD

**Issue by russorat** [influxdata/community-templates#29]
base it on 
 https://github.com/influxdata/telegraf/blob/master/plugins/inputs/jolokia2/examples/kafka.conf

**Comment by samhld** [comment]
I am 75% done with the Telegraf portion of this.  Dashboards and alerts will be the easier part so I should have this done by mid-late next week.

**Comment by samhld** [comment]
@russorat do you have an opinion on the inclusion of ZK and/or Burrow in this Template?  At first glance, I'd argue ZK is required but Burrow is not.  The stuff I'd want to see from Burrow I could see with a) appropriate metrics from the broker side and/or b) monitoring the producers/consumers with Telegraf separately.

**Comment by russorat** [comment]
zookeeper is a requirement to run kafka still, so i would agree it's required.

burrow seems separate since not all kafka users leverage burrow.

**Comment by samhld** [comment]
@russorat yeah, monitoring ZK is for sure a required complement.  I was just thinking whether or not it should be its own Template.  I'm going to go with no for now and put both in this one!

**Comment by samhld** [comment]
Closed via #129
