### ISSUE TITLE
Display a legend for all charts displaying multiple lines

### ISSUE THREAD

**Issue by alsargent** [influxdata/community-templates#72]
**Template**: All, but especially the MySQL/Nginx, Docker, and Postgres/Apache templates.

**Describe the problem**
Legends aren't being displayed for charts with multiple lines. As a result, it's not clear what you're looking at.

**To Reproduce**

For example, look at the Nginx / MySQL template on https://github.com/influxdata/community-templates/blob/master/nginx_mysql/img/Dashboard.png:

![image](https://user-images.githubusercontent.com/20701/79622957-98005b80-80ce-11ea-9b79-e5ee3d3ed8f3.png)

There's a chart titled **reading/writing/waiting**. We see two lines plotted. But it's unclear which line is for reading, which is for writing, and which is for waiting.

Similarly, check out the Apache/Posgres template at https://github.com/influxdata/community-templates/tree/master/apache_postgresql:

![image](https://user-images.githubusercontent.com/20701/79623106-4ad0b980-80cf-11ea-8cef-692a020f03d4.png)

There are several lines in the **Connections** chart. What do they all mean?

In the Docker template (https://github.com/influxdata/community-templates/tree/master/docker) we have a chart titled **Number of Docker containers**, which multiple lines. I'm guessing each line corresponds to a host, but I can't tell which line is for which host:

![image](https://user-images.githubusercontent.com/20701/79623189-adc25080-80cf-11ea-9daf-db2e03ed6f8e.png)

**Expected behavior**
When a chart has multiple lines, display a legend that indicates what each line corresponds to.

**Comment by alsargent** [comment]
@mhall119 I believe this auto-assigned to you as soon as I submitted this. Feel free to assign to someone else if needed.

**Comment by mhall119** [comment]
@alsargent the charts themselves have a legend, are you asking that we include that in the screen shots? Or that we provide the legend in the README for each template?

**Comment by mhall119** [comment]
Closing this based on past discussions, InfluxDB 2 doesn't currently show a legend that we can grab in the screenshot
