### ISSUE TITLE
All template resource `metadata.name` fields must be DNS Label name compliant

### ISSUE THREAD

**Issue by jsteenb2** [influxdata/community-templates#96]
this may require changes in existing templates. All metadata.name fields must satisfy [RFC 1123](https://tools.ietf.org/html/rfc1123). This is driven by the gitops of using tempaltes as a CRD within k8s. More details [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names).

tldr;

- [ ]  contain at most 63 characters
- [ ] contain only lowercase alphanumeric characters or ‘-’
- [ ] start with an alphanumeric character
- [ ] end with an alphanumeric character

**Comment by mhall119** [comment]
Reopening because a full fix requires more than just replacing _ with -, the old human-readable `metadata.name` needs to be moved to `spec.name`
